name: Build and Deploy Code

# on: push
# on: pull_request
# on: [push, pull_request]

on: [push, pull_request]

# it's also possible to provide specific branches
# on:
#     push:
#         branches: ["main"]  # only works with push to main branch
# #         branches:
# #             - "main"
# #             - "another branch"
#     pull_request:
#         branches:
#             - "test_branch"
#             - "another branch"

jobs:
    job1:
        runs-on: ubuntu-latest  # VM on which the job will be run
        steps:
            - name: pulling git repo
              uses: actions/checkout@v2  # grabbed from GitHub marketplace
            - name: say hi to Artur
              run: echo "hello Artur"