name: Build and Deploy Code

# on: push
# on: pull_request
# on: [push, pull_request]

on: [push, pull_request]

# it's also possible to provide specific branches
# on:
#     push:
#         branches: ["main"]  # only works with push to main branch
# #         branches:
# #             - "main"
# #             - "another branch"
#     pull_request:
#         branches:
#             - "test_branch"
#             - "another branch"

jobs:
    job1:
        runs-on: ubuntu-latest  # VM on which the job will be run
        steps:
            - name: pulling git repo
              uses: actions/checkout@v2  # grabbed from GitHub marketplace
#             - name: say hi to Artur
#               run: echo "hello Artur"
            # pre-build GitHub action - grabbed from GitHub marketplace
            - name: install Python version 3.10
              uses: actions/setup-python@v2
              with:
                python-version: "3.10"
            - name: update pip
              run: python -m pip install --upgrade pip  # runs command on Linux shell
            - name: install all dependencies
              run: pip install -r requirements.txt
            - name: test with pytest
              run: |
                pip install pytest
                pytest
